# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3d6dc0896602dbc531bf1e8bbeb19f2f6ac40fff0894c578e7907b6cce0742a14410f810d79f718dafdac45b88ae10cf1b687e91feba5d0e48c708b0e6e10a6

test:
  secret_key_base: f9d21bf326646abc5483d29c92254c4e9216f9832f1ba95d1944ca630ccff091955d7bcbec932c67c7fb6f3c14bf100142c2161cd83a3b91ab629685b3c3a613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
